import argparse
import logging
import pathlib
import subprocess
import sys
import tomllib

from . import __version__
from .cursorgen import cursorfile_from_ani

logger = logging.getLogger(__package__)


def main() -> int:
    handler = logging.StreamHandler(stream=sys.stderr)
    formatter = logging.Formatter(fmt="%(levelname)s %(message)s")
    handler.setFormatter(formatter)

    logger.addHandler(handler)
    logger.setLevel(logging.INFO)

    # Argument parsing
    parser = argparse.ArgumentParser(
        prog="win2xcursor",
        description="Python script to transform .ani files into xcursors",
        epilog="This script expects [path]/[theme] to be an existing directory with a config.toml, and your ani files to be stored in [path]/[theme]/ani/",
    )
    parser.add_argument(
        "--path",
        help="Path base where the new cursor will reside. Defaults to ~/.local/share/icons",
        type=pathlib.Path,
        default=pathlib.Path.home().joinpath(".local", "share", "icons"),
    )
    parser.add_argument(
        "--theme",
        help="Name to use for your new cursor.",
        type=str,
        required=True,
    )
    parser.add_argument(
        "-V",
        "--version",
        action="version",
        version=f"{__package__} {__version__}",
    )
    args = parser.parse_args()

    # Where X11 searches for cursor themes.
    icons_dir: pathlib.Path = args.path

    # Path to the custom cursor theme.
    theme_dir = icons_dir.joinpath(args.theme)

    # Contains all of the ANI files.
    ani_dir = theme_dir.joinpath("ani")

    # Read and parse config file
    config_file = theme_dir.joinpath("config.toml")
    with open(config_file, "rb") as f:
        config = tomllib.load(f)

    if not config.get("cursor"):
        logger.error(f"No cursors specified in {config_file}")
        return 1

    scale = max(1, int(config.get("scale", 1)))

    for cursor in config["cursor"][:]:
        if (
            not cursor.get("name")
            or not cursor.get("file")
            or cursor.get("aliases", None) is None
        ):
            logger.error(f"Missing property on cursor {cursor}")
            logger.error(
                "expected: [[cursor]]\nfile = ...\nname = ...\naliases = [...]"
            )
            logger.error(
                "Please refer to the config.toml template to see how to fill these values"
            )
            return 1
        if not (cursor_file := ani_dir.joinpath(cursor["file"])).exists():
            logger.info(f"Cannot find file {cursor_file}, skipping")
            config["cursor"].remove(cursor)

    # ======================================================================= #
    # xcursorfiles    contains all .cursor files generated by the script      #
    # frames          contains PNG files extracted from all .ani              #
    # cursors         contains the final cursors generated via xcursorgen     #
    # ======================================================================= #
    # You can delete the xcursorfiles and frames directories after running    #
    # the script, I'll leave them there so the process is understood a bit    #
    # better and to manually handle part of the process if the script fails   #
    # ======================================================================= #

    # PNGs extracted from the ANI files.
    frames_dir = theme_dir.joinpath("frames")
    frames_dir.mkdir(parents=True, exist_ok=True)

    # Generated `.cursor` files.
    xcursorfiles_dir = theme_dir.joinpath("xcursorfiles")
    xcursorfiles_dir.mkdir(parents=True, exist_ok=True)

    # Generated Xcursors
    cursors_dir = theme_dir.joinpath("cursors")
    cursors_dir.mkdir(parents=True, exist_ok=True)

    # Main script

    print("=" * 80, file=sys.stderr)
    print("WIN2XCUR PYTHON SCRIPT".center(80, " "), file=sys.stderr)
    print("=" * 80, file=sys.stderr)

    for cursor in config["cursor"]:
        logger.info(f"Creating .cursor file for {cursor['file']}")

        assert "file" in cursor, cursor.keys()
        ani_file = ani_dir.joinpath(cursor["file"])
        cursorfile = cursorfile_from_ani(
            ani_file,
            xcursorfiles_dir,
            frames_dir,
            scale,
        )

        assert "name" in cursor, cursor.keys()
        xcursor_file = cursors_dir.joinpath(cursor["name"])

        # create the cursor with xcursorgen
        logger.info(f"Creating cursor: {xcursor_file.name}")
        subprocess.run(
            [
                "xcursorgen",
                cursorfile,
                xcursor_file,
            ],
            check=True,
            cwd=theme_dir,
        )

        # create all defined aliases
        for alias in cursor["aliases"]:
            logger.info(f"Creating alias: {alias}")
            alias_file = cursors_dir.joinpath(alias)

            subprocess.run(
                [
                    "ln",
                    "-s",
                    xcursor_file,
                    alias_file,
                ],
                check=True,
                cwd=theme_dir,
            )

        print()
        print("-" * 80, file=sys.stderr, end="\n\n")

    # finally, create the index.theme
    index_theme = theme_dir.joinpath("index.theme")
    logger.info(f"Writing {index_theme.name}")
    with open(index_theme, "w") as f:
        f.write("[Icon Theme]\n")
        f.write(f"Name={args.theme}\n")
        f.write("Inherits=breeze_cursors\n")  # defaults for missing icons

    logger.info("Finished creating cursor!🚀🚀")
    return 0


if __name__ == "__main__":
    sys.exit(main())
